# Generated by Django 2.1.5 on 2019-01-27 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_typo_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
    ]
