# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170703_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='clef',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
