# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 22:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_adhesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhesion',
            name='adherent',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
