from django.urls import path, re_path

from . import views

app_name = 'media'
urlpatterns = [
    path('add_auteur/', views.add_auteur, name='add-auteur'),
    re_path(r'^edit_auteur/(?P<auteurid>[0-9]+)$', views.edit_auteur,
            name='edit-auteur'),
    re_path(r'^del_auteur/(?P<auteurid>[0-9]+)$', views.del_auteur,
            name='del-auteur'),
    path('index_auteurs/', views.index_auteurs, name='index-auteurs'),
    re_path(r'^history/(?P<object>auteur)/(?P<id>[0-9]+)$', views.history,
            name='history'),
    path('add_jeu/', views.add_jeu, name='add-jeu'),
    re_path(r'^edit_jeu/(?P<jeuid>[0-9]+)$', views.edit_jeu, name='edit-jeu'),
    re_path(r'^del_jeu/(?P<jeuid>[0-9]+)$', views.del_jeu, name='del-jeu'),
    path('index_jeux/', views.index_jeux, name='index-jeux'),
    re_path(r'^history/(?P<object>jeu)/(?P<id>[0-9]+)$', views.history,
            name='history'),
    path('add_media/', views.add_media, name='add-media'),
    re_path(r'^edit_media/(?P<mediaid>[0-9]+)$', views.edit_media,
            name='edit-media'),
    re_path(r'^del_media/(?P<mediaid>[0-9]+)$', views.del_media,
            name='del-media'),
    path('index_medias/', views.index_medias, name='index-medias'),
    re_path(r'^history/(?P<object>media)/(?P<id>[0-9]+)$', views.history,
            name='history'),
    re_path(r'^add_emprunt/(?P<userid>[0-9]+)$', views.add_emprunt,
            name='add-emprunt'),
    re_path(r'^retour_emprunt/(?P<empruntid>[0-9]+)$', views.retour_emprunt,
            name='retour-emprunt'),
    re_path(r'^edit_emprunt/(?P<empruntid>[0-9]+)$', views.edit_emprunt,
            name='edit-emprunt'),
    re_path(r'^del_emprunt/(?P<empruntid>[0-9]+)$', views.del_emprunt,
            name='del-emprunt'),
    path('index_emprunts/', views.index, name='index'),
    re_path(r'^history/(?P<object>emprunt)/(?P<id>[0-9]+)$', views.history,
            name='history'),
    path('', views.index, name='index'),
]
