# Generated by Django 2.1.5 on 2019-01-24 08:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [('media', '0001_initial'),
                ('media', '0002_media_auteur'),
                ('media', '0003_auto_20170629_1536'),
                ('media', '0004_auto_20170629_1539'),
                ('media', '0005_auto_20170630_1551'),
                ('media', '0006_jeu'),
                ('media', '0007_auto_20170704_0138'),
                ('media', '0008_auto_20170704_2047')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('date_emprunt',
                 models.DateTimeField(help_text='%d/%m/%y %H:%M:%S')),
                ('date_rendu',
                 models.DateTimeField(help_text='%d/%m/%y %H:%M:%S')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('cote', models.CharField(max_length=31)),
                ('auteur', models.ManyToManyField(to='media.Auteur')),
            ],
        ),
        migrations.AddField(
            model_name='emprunt',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to='media.Media'),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='permanencier_emprunt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    related_name='user_permanencier_emprunt',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='permanencier_rendu',
            field=models.ForeignKey(blank=True, null=True,
                                    on_delete=django.db.models.deletion.PROTECT,
                                    related_name='user_permanencier_rendu',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emprunt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_rendu',
            field=models.DateTimeField(blank=True,
                                       help_text='%d/%m/%y %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='emprunt',
            name='date_rendu',
            field=models.DateTimeField(blank=True,
                                       help_text='%d/%m/%y %H:%M:%S',
                                       null=True),
        ),
        migrations.CreateModel(
            name='Jeu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('duree', models.CharField(
                    choices=[('-1h', '-1h'), ('1-2h', '1-2h'), ('2-3h', '2-3h'),
                             ('3-4h', '3-4h'), ('4h+', '4h+')],
                    max_length=255)),
                ('nombre_joueurs_min', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(1)])),
                ('nombre_joueurs_max', models.IntegerField(
                    validators=[django.core.validators.MinValueValidator(1)])),
                ('comment',
                 models.CharField(blank=True, help_text='Commentaire',
                                  max_length=255, null=True)),
                ('proprietaire',
                 models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
