# Generated by Django 2.1.5 on 2019-01-27 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20190127_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprunt',
            options={'ordering': ['-date_emprunt'], 'permissions': (('my_view', 'Can view his borrowed media'),), 'verbose_name': 'borrowed media', 'verbose_name_plural': 'borrowed medias'},
        ),
    ]
