# Generated by Django 2.1.5 on 2019-01-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190128_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedmedia',
            name='borrowed_at',
            field=models.DateTimeField(verbose_name='borrowed at'),
        ),
        migrations.AlterField(
            model_name='borrowedmedia',
            name='given_back_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='given back at'),
        ),
    ]
