# Generated by Django 2.1.5 on 2019-01-30 21:02

from django.db import migrations, models
import media.fields
import media.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_add_game_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='binding',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='binding'),
        ),
        migrations.AddField(
            model_name='media',
            name='edition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='edition'),
        ),
        migrations.AddField(
            model_name='media',
            name='isbn',
            field=media.fields.ISBNField(blank=True, max_length=28, null=True, validators=[media.validators.isbn_validator], verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='media',
            name='published_on',
            field=models.DateField(blank=True, null=True, verbose_name='published on'),
        ),
        migrations.AddField(
            model_name='media',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='publisher'),
        ),
    ]
