# Generated by Django 2.1.5 on 2019-01-27 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_use_django_contrib_auth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adhesion',
            old_name='adherent',
            new_name='member',
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='member'),
        ),
        migrations.RenameField(
            model_name='adhesion',
            old_name='annee_debut',
            new_name='start_at',
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='start_at',
            field=models.IntegerField(unique=True, verbose_name='start at'),
        ),
        migrations.RenameField(
            model_name='adhesion',
            old_name='annee_fin',
            new_name='end_at',
        ),
        migrations.AlterField(
            model_name='adhesion',
            name='end_at',
            field=models.IntegerField(unique=True, verbose_name='end at'),
        ),
        migrations.RenameField(
            model_name='clef',
            old_name='commentaire',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='clef',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.RenameField(
            model_name='clef',
            old_name='nom',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='clef',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name'),
        ),
        migrations.RenameField(
            model_name='clef',
            old_name='proprio',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='clef',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='adresse',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='comment'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='maxemprunt',
            new_name='max_borrowed',
        ),
        migrations.AlterField(
            model_name='user',
            name='max_borrowed',
            field=models.IntegerField(default=5, verbose_name='maximum simultaneous borrowed books'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.IntegerField(choices=[(0, 'STATE_ACTIVE'), (1, 'STATE_DISABLED'), (2, 'STATE_ARCHIVE')], default=0, verbose_name='state'),
        ),
        migrations.RenameField(
            model_name='user',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='phone'),
        ),
    ]
