# Generated by Django 2.1.5 on 2019-01-30 20:11

from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    replaces = [('users', '0007_auto_20190130_2107'), ('users', '0008_auto_20190130_2108')]

    dependencies = [
        ('users', '0006_remove_user_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clef',
            new_name='Key',
        ),
        migrations.RenameModel(
            old_name='Adhesion',
            new_name='Membership',
        ),
    ]
