# Generated by Django 2.1.5 on 2019-01-27 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20190127_1624'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auteur',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='Jeu',
            new_name='Game',
        ),
    ]
