# Generated by Django 2.1.5 on 2019-01-28 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_translate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedmedia',
            name='borrowed_with_permanent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_borrowed_with_permanent', to=settings.AUTH_USER_MODEL, verbose_name='borrowed with permanent'),
        ),
        migrations.AlterField(
            model_name='borrowedmedia',
            name='given_back_with_permanent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_given_back_with_permanent', to=settings.AUTH_USER_MODEL, verbose_name='given back with permanent'),
        ),
    ]
