# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170629_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='auteur',
        ),
        migrations.AddField(
            model_name='media',
            name='auteur',
            field=models.ManyToManyField(to='media.Auteur'),
        ),
    ]
