# Generated by Django 2.1.5 on 2019-01-30 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20190129_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'game type',
                'verbose_name_plural': 'game types',
                'ordering': ['-name'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='media.GameType', verbose_name='game type'),
        ),
        migrations.AlterField(
            model_name='game',
            name='length',
            field=models.CharField(blank=True, choices=[('-1h', '-1h'), ('1-2h', '1-2h'), ('2-3h', '2-3h'), ('3-4h', '3-4h'), ('4h+', '4h+')], max_length=255, null=True, verbose_name='length'),
        ),
        migrations.AlterField(
            model_name='game',
            name='max_players',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='maximum number of players'),
        ),
        migrations.AlterField(
            model_name='game',
            name='min_players',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='minimum number of players'),
        ),
        migrations.AlterField(
            model_name='media',
            name='side_title',
            field=models.CharField(blank=True, max_length=31, null=True, verbose_name='side title'),
        ),
        migrations.AddField(
            model_name='game',
            name='box_depth',
            field=models.FloatField(blank=True, null=True, verbose_name='box depth'),
        ),
        migrations.AddField(
            model_name='game',
            name='box_length',
            field=models.FloatField(blank=True, null=True, verbose_name='box length'),
        ),
        migrations.AddField(
            model_name='game',
            name='box_width',
            field=models.FloatField(blank=True, null=True, verbose_name='box width'),
        ),
        migrations.AddField(
            model_name='game',
            name='last_time_week_game',
            field=models.DateField(blank=True, null=True, verbose_name='last time it was the week game'),
        ),
    ]
