# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 23:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_jeu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jeu',
            name='duree',
            field=models.CharField(choices=[('1h-', '1h-'), ('1-2h', '1-2h'), ('2-3h', '2-3h'), ('4h+', '4h+')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='nombre_joueurs_max',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='nombre_joueurs_min',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
