# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20170704_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auteur',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='jeu',
            name='duree',
            field=models.CharField(choices=[('-1h', '-1h'), ('1-2h', '1-2h'), ('2-3h', '2-3h'), ('3-4h', '3-4h'), ('4h+', '4h+')], max_length=255),
        ),
    ]
